# Generated by Django 5.0 on 2024-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Kerla', 'Kerla'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Andhra Pradhesh', 'Andhra Pradhesh'), ('Punjab', 'Punjab'), ('Assam', 'Assam')], max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(),
        ),
    ]
