# Generated by Django 5.0 on 2024-01-02 15:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=110),
        ),
    ]
